services:
  - type: web
    name: sdg1-backend
    runtime: node
    rootDir: apps/backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL_NAME
        value: gpt-4o-mini
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: REDIS_URL
        sync: false
  - type: web
    name: sdg1-frontend
    runtime: static
    rootDir: apps/frontend
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false

databases:
  - name: sdg1-db
    databaseName: sdg1
    user: sdg1
    plan: free
    ipAllowList: []
    postgresExtensions:
      - postgis
